# Telemindex

## Importamos librerías

In [2]:
#En pruebas: Uso de la variables mes_seleccionado definida en el archivo 'globals.py'

In [3]:
import pandas as pd
import plotly.express as px
import globals

## Importamos el fichero excel

In [4]:
df_in=pd.read_excel('data.xlsx')
df_in

,fecha,año,mes,mes_nombre,dia,dia_semana,hora,dh_6p,dh_3p,pmh,...,perd_3.0,perd_6.1,pyc_2.0,pyc_3.0,pyc_6.1,precio_2.0,precio_3.0,precio_6.1,demanda_GWh,pvpc
0,2024-07-31,2024,7,julio,31,miércoles,23,P2,P2,116.98,...,0.167065,0.064917,27.963,30.938,21.531,180.005830,184.997444,161.749537,31.94,173.51
1,2024-07-31,2024,7,julio,31,miércoles,22,P2,P2,132.40,...,0.168950,0.065649,27.963,30.938,21.531,199.807729,205.013074,179.865990,34.43,190.91
2,2024-07-31,2024,7,julio,31,miércoles,21,P1,P1,142.48,...,0.149890,0.060498,76.974,48.443,35.204,262.525304,234.222198,205.776537,35.43,251.28
3,2024-07-31,2024,7,julio,31,miércoles,20,P1,P1,117.53,...,0.148580,0.059969,76.974,48.443,35.204,236.598406,208.316171,181.979368,35.51,222.24
4,2024-07-31,2024,7,julio,31,miércoles,19,P1,P1,111.14,...,0.147564,0.059559,76.974,48.443,35.204,221.862168,193.591748,168.457925,35.43,214.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13872,2023-01-01,2023,1,enero,1,domingo,4,P6,P3,0.00,...,0.278267,0.119037,3.175,2.370,1.426,57.258845,56.453845,48.772747,0.00,NaN
13873,2023-01-01,2023,1,enero,1,domingo,3,P6,P3,0.00,...,0.271627,0.116196,3.175,2.370,1.426,54.732076,53.927076,46.681249,0.00,NaN
13874,2023-01-01,2023,1,enero,1,domingo,2,P6,P3,0.00,...,0.260780,0.111556,3.175,2.370,1.426,54.343489,53.538489,46.538253,0.00,NaN
13875,2023-01-01,2023,1,enero,1,domingo,1,P6,P3,0.00,...,0.246510,0.105451,3.175,2.370,1.426,39.480134,38.675134,33.622745,0.00,NaN
13876,2023-01-01,2023,1,enero,1,domingo,0,P6,P3,0.00,...,0.236678,0.101246,3.175,2.370,1.426,38.214706,37.409706,32.628395,0.00,NaN

## Filtramos por el año 2024

In [5]:
año=2024 #con cambiar este valor ya sobra para filtrar la tabla
filtro_año=df_in['año']==año
dffa =df_in[filtro_año].set_index('fecha')
dffa

,año,mes,mes_nombre,dia,dia_semana,hora,dh_6p,dh_3p,pmh,ssaa,...,perd_3.0,perd_6.1,pyc_2.0,pyc_3.0,pyc_6.1,precio_2.0,precio_3.0,precio_6.1,demanda_GWh,pvpc
fecha,,,,,,,,,,,,,,,,,,,,,
2024-07-31,2024,7,julio,31,miércoles,23,P2,P2,116.98,8.58,...,0.167065,0.064917,27.963,30.938,21.531,180.005830,184.997444,161.749537,31.94,173.51
2024-07-31,2024,7,julio,31,miércoles,22,P2,P2,132.40,9.82,...,0.168950,0.065649,27.963,30.938,21.531,199.807729,205.013074,179.865990,34.43,190.91
2024-07-31,2024,7,julio,31,miércoles,21,P1,P1,142.48,11.53,...,0.149890,0.060498,76.974,48.443,35.204,262.525304,234.222198,205.776537,35.43,251.28
2024-07-31,2024,7,julio,31,miércoles,20,P1,P1,117.53,14.44,...,0.148580,0.059969,76.974,48.443,35.204,236.598406,208.316171,181.979368,35.51,222.24
2024-07-31,2024,7,julio,31,miércoles,19,P1,P1,111.14,8.31,...,0.147564,0.059559,76.974,48.443,35.204,221.862168,193.591748,168.457925,35.43,214.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-01,2024,1,enero,1,lunes,4,P6,P3,42.50,22.69,...,0.276025,0.118077,2.752,2.192,1.276,92.254375,91.694375,79.699695,18.14,110.16
2024-01-01,2024,1,enero,1,lunes,3,P6,P3,43.50,20.86,...,0.268402,0.114816,2.752,2.192,1.276,90.651121,90.091121,78.531790,18.87,109.28
2024-01-01,2024,1,enero,1,lunes,2,P6,P3,47.50,19.05,...,0.257177,0.110015,2.752,2.192,1.276,92.667768,92.107768,80.666431,20.03,110.77
2024-01-01,2024,1,enero,1,lunes,1,P6,P3,50.09,20.75,...,0.243274,0.104067,2.752,2.192,1.276,97.087032,96.527032,85.048550,21.20,111.12
2024-01-01,2024,1,enero,1,lunes,0,P6,P3,63.33,15.41,...,0.237544,0.101616,2.752,2.192,1.276,106.575554,106.015554,93.695892,21.86,123.84

### Obtenemos el último registro

In [6]:
#usado como texto adicional en el gráfico si rango = todo el año
max_reg=dffa.index.max().strftime('%d-%m-%Y')
max_reg
texto_graf=f'Último día registrado: {max_reg}'

### Interacción en streamlit: Listado de meses disponibles para usar en un select_box

In [7]:
lista_meses=dffa['mes_nombre'].unique().tolist()
lista_meses

['julio', 'junio', 'mayo', 'abril', 'marzo', 'febrero', 'enero']

In [8]:
orden_meses = {
    'enero': 1,
    'febrero': 2,
    'marzo': 3,
    'abril': 4,
    'mayo': 5,
    'junio': 6,
    'julio': 7,
    'agosto': 8,
    'septiembre': 9,
    'octubre': 10,
    'noviembre': 11,
    'diciembre': 12
}

In [9]:
lista_meses=sorted(lista_meses,key=lambda x:orden_meses[x])
lista_meses

['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio']

## Telemindex horario para streamlit

### Inicializamos dffm, que es el la tabla filtrada por el usuario

In [10]:
dffa_copia=dffa.copy()

## Filtramos el mes seleccionado por el usuario

In [11]:
def filtrar_mes(mes_seleccionado=None):
        if mes_seleccionado is None: 
                dffm=dffa_copia
        else:
                mes_filtro=dffa_copia['mes_nombre']==mes_seleccionado
                dffm=dffa_copia[mes_filtro]
                #texto_graf=f'{mes}'
        return dffm #,texto_graf

In [12]:
def aplicar_margen(mes_seleccionado,margen_aplicado):
    dffa_copia['precio_2.0']=dffa['precio_2.0'] #+=margen_aplicado #=dffm['precio_2.0']+margen
    dffa_copia['precio_3.0']=dffa['precio_3.0'] #+=margen_aplicado #dffm['precio_3.0']+margen
    dffa_copia['precio_6.1']=dffa['precio_6.1'] #+=margen_aplicado #dffm['precio_6.1']+margen
    dffa_copia['precio_2.0']+=margen_aplicado #=dffm['precio_2.0']+margen
    dffa_copia['precio_3.0']+=margen_aplicado #dffm['precio_3.0']+margen
    dffa_copia['precio_6.1']+=margen_aplicado #dffm['precio_6.1']+margen
    
    filtrar_mes(mes_seleccionado)

    return dffa_copia

### De esta tabla sale el gráfico

In [ ]:
def pt1():
    dffm=filtrar_mes(globals.mes_seleccionado)
    #texto_graf=texto_graf
    pt1=dffm.pivot_table(
        values=['spot','precio_2.0','precio_3.0','precio_6.1'],
        index='hora',
        aggfunc='mean'
    ).reset_index()
    
    return pt1

In [ ]:
pt1()

    hora  precio_2.0  precio_3.0  precio_6.1       spot
0      0   69.771131   69.211131   61.724454  45.166209
1      1   66.008388   65.448388   58.178551  40.651978
2      2   64.712992   64.152992   56.925877  38.450773
3      3   64.522901   63.962901   56.721190  37.104725
4      4   63.990766   63.430766   56.253126  36.358132
5      5   65.684584   65.124584   57.851242  38.128297
6      6   71.374652   70.814652   63.280464  43.276703
7      7   84.786716   84.226716   75.772935  53.101593
8      8  101.309032   92.941187   81.341168  50.513626
9      9   84.391298   84.586207   72.985647  39.172967
10    10  104.637726   69.540969   59.392714  30.894670
11    11   97.698893   62.604227   53.057671  25.428846
12    12   95.839120   60.745821   51.387753  23.465934
13    13   94.321209   59.229944   50.048615  21.779780
14    14   57.968045   49.738393   42.506797  20.839725
15    15   58.305990   50.090279   42.704993  20.443846
16    16   61.709305   53.507766   45.684695  22.397473
17    17   70.246938   62.085177   53.317440  28.048022
18    18  116.459677   81.378538   69.770938  36.552802
19    19  136.255660  101.187280   87.722277  49.522418
20    20  152.361684  117.285830  102.343907  62.416868
21    21  153.354083  118.257420  103.291785  66.506868
22    22  108.412023   99.940262   87.373315  58.989451
23    23   98.509585   90.079693   78.352868  49.971813

### Transponemos para visualizar en stremalit

In [ ]:
def pt1_trans():
    pt2=pt1()
    pt1_trans=pt2.transpose()
    pt1_trans=pt1_trans.drop(['hora'])
    pt1_trans.columns.name='peajes'
    pt1_trans=pt1_trans.round(2)
    
    return pt1_trans

### Gráfico de salida para visualizar en streamlit

In [ ]:
def graf_pt1():
    pt2=pt1()
    colores_precios = {'precio_2.0': 'goldenrod', 'precio_3.0': 'darkred', 'precio_6.1': 'blue'}
    graf_pt1=px.line(pt2,x='hora',y=['precio_2.0','precio_3.0','precio_6.1'],
        height=600,
        width=1000,
        title="Telemindex 2024: Precios medios horarios de indexado según tarifas de acceso",
        labels={'value':'€/MWh','variable':'Precios s/ ATR'},
        color_discrete_map=colores_precios,
    )
    graf_pt1.update_traces(line=dict(width=4))
    graf_pt1.add_annotation(
        dict(
            font=dict(size=12),
            x=0.5,
            y=1.05,
            showarrow=False,
            text=texto_graf,
            xref="paper",
            yref="paper"
        )
    )
    graf_pt1.update_layout(
        margin=dict(t=100),
        title_font_size=16,
    )
    graf_pt1=graf_pt1.add_bar(y=pt2['spot'], name='spot', marker_color='green', width=0.5)
    
    return graf_pt1

## Obtención de la tabla resumen de precios

In [ ]:
#dffm=filtrar_mes(globals.mes_seleccionado)
def pt5_trans():
        dffm=filtrar_mes(globals.mes_seleccionado)    
        pt3=dffm.pivot_table(
                values=['precio_2.0'],
                aggfunc='mean',
                index='dh_3p'
                )
        pt4=dffm.pivot_table(
                values=['precio_3.0','precio_6.1'],
                aggfunc='mean',
                index='dh_6p',
                )
        pt5=pd.concat([pt3,pt4],axis=1)
        
        
        media_20=dffm['precio_2.0'].mean()
        media_30=dffm['precio_3.0'].mean()
        media_61=dffm['precio_6.1'].mean()
        precios_medios=[media_20,media_30,media_61]
        pt5_trans=pt5.transpose()
        pt5_trans['Media']=precios_medios
        pt5_trans=pt5_trans.div(10)
        pt5_trans=pt5_trans.round(1)
        pt5_trans=pt5_trans.fillna('')

        return pt5_trans, media_20,media_30,media_61