In [6]:
import pandas as pd
import openpyxl

In [9]:
# Cargar todas las tablas del archivo (incluyendo nombres de tablas definidas en Excel)
file_path = r"C:\Users\jovid\Documents\015 JOSE\070 ENERGIA\002 HERRAMIENTAS EXCEL\FUNCIONALES\004 LUZ componentes regulados.xlsx"

In [ ]:
# Cargar todas las hojas
sheets_dict = pd.read_excel(file_path, sheet_name=None, engine="openpyxl")

# Crear un diccionario con todas las tablas identificadas
tablas = {sheet_name: df for sheet_name, df in sheets_dict.items()}

# Acceder a cualquier tabla por su nombre de hoja
df_ppcc = tablas["PPCC"]
df_osom = tablas['OSOM']
df_perdidas_boe = tablas['PERDIDAS']
df_pycs_energia = tablas['PYC_E']

  fecha_inicio fecha_final periodo     2.0TD     3.0TD     6.1TD     6.2TD  \
0   2021-06-01  2021-12-31      P1  0.001780  0.002406  0.001031  0.001031
1   2021-06-01  2021-12-31      P2  0.000297  0.001111  0.000476  0.000476
2   2021-06-01  2021-12-31      P3  0.000000  0.000740  0.000317  0.000317
3   2021-06-01  2021-12-31      P4       NaN  0.000555  0.000238  0.000238
4   2021-06-01  2021-12-31      P5       NaN  0.000555  0.000238  0.000238

      6.3TD     6.4TD
0  0.001031  0.001031
1  0.000476  0.000476
2  0.000317  0.000317
3  0.000238  0.000238
4  0.000238  0.000238

In [13]:
df_ppcc

,fecha_inicio,fecha_final,periodo,2.0TD,3.0TD,6.1TD,6.2TD,6.3TD,6.4TD
0,2021-06-01,2021-12-31,P1,0.001780,0.002406,0.001031,0.001031,0.001031,0.001031
1,2021-06-01,2021-12-31,P2,0.000297,0.001111,0.000476,0.000476,0.000476,0.000476
2,2021-06-01,2021-12-31,P3,0.000000,0.000740,0.000317,0.000317,0.000317,0.000317
3,2021-06-01,2021-12-31,P4,NaN,0.000555,0.000238,0.000238,0.000238,0.000238
4,2021-06-01,2021-12-31,P5,NaN,0.000555,0.000238,0.000238,0.000238,0.000238
5,2021-06-01,2021-12-31,P6,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
6,2022-01-01,2022-12-31,P1,0.001444,0.001952,0.000837,0.000837,0.000837,0.000837
7,2022-01-01,2022-12-31,P2,0.000241,0.000902,0.000386,0.000386,0.000386,0.000386
8,2022-01-01,2022-12-31,P3,0.000000,0.000601,0.000257,0.000257,0.000257,0.000257
9,2022-01-01,2022-12-31,P4,NaN,0.000450,0.000193,0.000193,0.000193,0.000193
10,2022-01-01,2022-12-31,P5,NaN,0.000450,0.000193,0.000193,0.000193,0.000193
11,2022-01-01,2022-12-31,P6,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
12,2023-01-01,2024-02-14,P1,0.001068,0.001443,0.000619,0.000619,0.000619,0.000619
13,2023-01-01,2024-02-14,P2,0.000178,0.000667,0.000285,0.000285,0.000285,0.000285
14,2023-01-01,2024-02-14,P3,0.000000,0.000444,0.000190,0.000190,0.000190,0.000190
15,2023-01-01,2024-02-14,P4,NaN,0.000333,0.000143,0.000143,0.000143,0.000143
16,2023-01-01,2024-02-14,P5,NaN,0.000333,0.000143,0.000143,0.000143,0.000143
17,2023-01-01,2024-02-14,P6,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
18,2024-02-15,2024-12-31,P1,0.000926,0.001251,0.000537,0.000537,0.000537,0.000537
19,2024-02-15,2024-12-31,P2,0.000154,0.000578,0.000247,0.000247,0.000247,0.000247
20,2024-02-15,2024-12-31,P3,0.000000,0.000385,0.000165,0.000165,0.000165,0.000165
21,2024-02-15,2024-12-31,P4,NaN,0.000289,0.000124,0.000124,0.000124,0.000124
22,2024-02-15,2024-12-31,P5,NaN,0.000289,0.000124,0.000124,0.000124,0.000124
23,2024-02-15,2024-12-31,P6,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
24,2025-01-01,2025-12-31,P1,0.000844,0.001141,0.000490,0.000490,0.000490,0.000490
25,2025-01-01,2025-12-31,P2,0.000140,0.000527,0.000225,0.000225,0.000225,0.000225
26,2025-01-01,2025-12-31,P3,0.000000,0.000351,0.000150,0.000150,0.000150,0.000150
27,2025-01-01,2025-12-31,P4,NaN,0.000264,0.000113,0.000113,0.000113,0.000113
28,2025-01-01,2025-12-31,P5,NaN,0.000264,0.000113,0.000113,0.000113,0.000113
29,2025-01-01,2025-12-31,P6,NaN,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:

@st.cache_data(ttl = 10000)
def download_esios_id(id, fecha_ini, fecha_fin, agrupacion):
                       
    cab = dict()
    cab ['x-api-key'] = st.secrets['ESIOS_API_KEY']
    url_id = 'https://api.esios.ree.es/indicators'
    url = f'{url_id}/{id}?geo_ids[]=3&start_date={fecha_ini}T00:00:00&end_date={fecha_fin}T23:59:59&time_trunc={agrupacion}'
    print(url)
    datos_origen = requests.get(url, headers = cab).json()
    
    #arreglamos los datos origen    
    datos  =pd.DataFrame(datos_origen['indicator']['values'])
    datos = (datos
        .assign(datetime=lambda vh_: pd #formateamos campo fecha, desde un str con diferencia horaria a un naive
            .to_datetime(vh_['datetime'],utc=True)  # con la fecha local
            .dt
            .tz_convert('Europe/Madrid')
            .dt
            .tz_localize(None)
        )   
        .loc[:,['datetime','value']]
    )
    datos['fecha'] = datos['datetime'].dt.date
    datos['fecha'] = pd.to_datetime(datos['fecha'], format = '%d/%m/%Y')
    datos['año'] = datos['datetime'].dt.year
    datos['mes'] = datos['datetime'].dt.month
    datos['dia'] = datos['datetime'].dt.day
    datos['hora'] = datos['datetime'].dt.hour
    meses_español = {1: "ene", 2: "feb", 3: "mar", 4: "abr", 5: "may", 6: "jun",
                 7: "jul", 8: "ago", 9: "sep", 10: "oct", 11: "nov", 12: "dic"}
    datos['mes_nombre'] = datos['mes'].map(meses_español)
    datos.set_index('datetime', inplace = True)
    
    #creamos df con las medias diarias
    datos_dia = datos.copy()
    #datos_dia=datos.reset_index()
    datos_dia = datos.drop(columns = ['hora'])
    #datos_dia['fecha'] =pd.to_datetime(datos['fecha'],format='%d/%m/%Y')
    #datos_dia['mes_nombre']=datos_dia['mes'].map(meses_español)
    datos_dia = datos_dia.groupby('fecha').agg({
        'value':'mean',
        'dia':'first',
        'mes':'first',
        'año':'first',
        'mes_nombre':'first'

    })
    #datos_dia=datos_dia.resample('D').mean()
    datos_dia['value']=datos_dia['value'].round(2)
    datos_dia[['dia','mes','año']]=datos_dia[['dia','mes','año']].astype(int)
    datos_dia.reset_index(inplace=True)
    #print (datos_dia)
     
    
    #calculams medias mensuales-----------------------------
    datos_mes=datos_dia.copy()
    datos_mes=datos_dia.drop(columns=['fecha', 'dia'])
    datos_mes=datos_mes.groupby('mes').agg({
        'value':'mean',
        'año':'first',
        'mes_nombre':'first'
    }).reset_index()
    datos_mes['value']=datos_mes['value'].round(2)
    datos_mes[['mes','año']]=datos_mes[['mes','año']].astype(int)
    
    media_mensual=round(datos_dia['value'].mean(),2)
    
    df_fila_espacio = pd.DataFrame({'mes': [None], 'value': [0], 'año': [None], 'mes_nombre': ['']})
    df_fila_media=pd.DataFrame({'mes': [13],'value':[media_mensual],'año':['2024'],'mes_nombre':['media']})
    datos_mes=pd.concat([datos_mes, df_fila_espacio, df_fila_media], ignore_index=True)
    print(datos_mes)
    
    # definimos escala en rango y color
    datos_limites = {
        'rango': [-10, 20.01, 40.01, 60.01, 80.01, 100.01, 120.01, 140.01, 10000], #9 elementos
        'valor_asignado': ['muy bajo', 'bajo', 'medio', 'alto', 'muy alto', 'chungo', 'xtrem', 'defcon3', 'defcon2'],
    }
    df_limites=pd.DataFrame(datos_limites)
    etiquetas = df_limites['valor_asignado'][:-1]
    datos_horarios=datos.copy()
    datos_horarios['escala']=pd.cut(datos_horarios['value'],bins=df_limites['rango'],labels=etiquetas,right=True)
    lista_escala=datos_horarios['escala'].unique()
    datos_dia['escala']=pd.cut(datos_dia['value'],bins=df_limites['rango'],labels=etiquetas,right=False)
    datos_mes['escala']=pd.cut(datos_mes['value'],bins=df_limites['rango'],labels=etiquetas,right=False)

    colores = {
        'muy bajo': 'lightgreen',
        'bajo': 'green',
        #'medio': 'blue',
        'medio': '#24d4ff',
        #'alto': 'orange',
        'alto': '#004280',
        #'muy alto': 'red',
        'muy alto': 'orange',
        #'chungo': 'purple',
        'chungo': 'red',
        #'xtrem':'black',
        'xtrem':'darkred',
        'defcon3': 'purple',
        'defcon2': 'purple',
    }

    datos_horarios['color']=datos_horarios['escala'].map(colores)
    datos_dia['color']=datos_dia['escala'].map(colores)

    valor_asignado_a_rango = {row['valor_asignado']: row['rango'] for _, row in df_limites.iterrows()}
    escala_horaria=['alto', 'medio', 'bajo', 'muy bajo', 'muy alto', 'chungo']
    escala_ordenada_hora = sorted(escala_horaria, key=lambda x: valor_asignado_a_rango[x], reverse=True)
    datos_horarios['escala']=pd.Categorical(datos_horarios['escala'],categories=escala_ordenada_hora, ordered=True)
    escala_dia=datos_dia['escala'].unique()
    escala_ordenada_dia = sorted(escala_dia, key=lambda x: valor_asignado_a_rango[x], reverse=True)
    datos_mes['color']=datos_mes['escala'].map(colores)
    escala_mes= datos_mes['escala'].unique()
    escala_ordenada_mes = sorted(escala_mes, key=lambda x: valor_asignado_a_rango[x], reverse=True)
    datos_dia['escala']=pd.Categorical(datos_dia['escala'],categories=escala_ordenada_dia, ordered=True)
    datos_mes['escala']=pd.Categorical(datos_mes['escala'],categories=escala_ordenada_mes, ordered=True)
    #print(datos_mes)

    datos_dia_queso=datos_dia.groupby(['escala'])['escala'].count()
    print(datos_dia_queso)
    datos_dia_queso=datos_dia_queso.reset_index(name='num_dias')
    print (datos_dia_queso)

    #GRÁFICO PRINCIPAL CON LOS PRECIOS MEDIOS DIARIOS DEL AÑO. ecv es escala cavero vidal-----------------------------------------------------------
    graf_ecv_anual=px.bar(datos_dia, x='fecha', y='value', 
        color='escala',
        color_discrete_map=colores,
        category_orders={'escala':escala_ordenada_dia},
        labels={'fecha':'fecha','value':'precio medio diario €/MWh', 'escala':'escala_cv'},
        title= f'Precios medios del mercado diario OMIE. Año {st.session_state.año_seleccionado}',
        hover_name='escala'
    )
    return